$ErrorActionPreference = "Stop"
Set-Location (Split-Path $MyInvocation.MyCommand.Path)

$py = Join-Path $PSScriptRoot "lib\venv\Scripts\python.exe"
$backend = Join-Path $PSScriptRoot "backend"
$envFile = Join-Path $PSScriptRoot ".env"

if (-not (Test-Path $py)) {
    Write-Host "[NetProof] venv not found - run bootstrap.ps1 first." -ForegroundColor Red
    exit 1
}

# Load .env (KEY=VALUE) into the process environment. Values already set in the
# shell win, so `$env:NETPROOF_ADMIN_PASS=...; .\run.ps1` still overrides. This
# makes run.ps1 honor the same .env that docker compose uses.
function Import-DotEnv([string]$Path) {
    if (-not (Test-Path $Path)) { return }
    foreach ($raw in Get-Content $Path) {
        $line = "$raw".Trim()
        if (-not $line -or $line.StartsWith("#")) { continue }
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
            $name = $Matches[1]
            $value = $Matches[2].Trim().Trim('"').Trim("'")
            if (-not (Test-Path "Env:$name")) { Set-Item -Path "Env:$name" -Value $value }
        }
    }
}

Import-DotEnv $envFile

# First-run convenience: if no admin password is configured anywhere, generate a
# strong random one and persist it to .env (gitignored). The "no default
# credentials" guarantee is preserved - the secret is random per install, never a
# known default - while a local `.\run.ps1` starts with no extra steps.
if (-not $env:NETPROOF_ADMIN_PASS) {
    $bytes = New-Object 'System.Byte[]' 24
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes); $rng.Dispose()
    $generated = -join ($bytes | ForEach-Object { $_.ToString("x2") })
    $user = if ($env:NETPROOF_ADMIN_USER) { $env:NETPROOF_ADMIN_USER } else { "admin" }

    if (-not (Test-Path $envFile)) {
        Set-Content -Path $envFile -Encoding ascii -Value @(
            "# Generated by run.ps1 on first start. Gitignored - do not commit.",
            "NETPROOF_ADMIN_USER=$user",
            "NETPROOF_ADMIN_PASS=$generated"
        )
    } else {
        Add-Content -Path $envFile -Encoding ascii -Value "NETPROOF_ADMIN_PASS=$generated"
        if (-not (Select-String -Path $envFile -Pattern '^\s*NETPROOF_ADMIN_USER\s*=' -Quiet)) {
            Add-Content -Path $envFile -Encoding ascii -Value "NETPROOF_ADMIN_USER=$user"
        }
    }

    $env:NETPROOF_ADMIN_USER = $user
    $env:NETPROOF_ADMIN_PASS = $generated
    Write-Host "  [NetProof] No admin password found - generated one and saved it to .env" -ForegroundColor Yellow
    Write-Host "             user: $user" -ForegroundColor Yellow
    Write-Host "             pass: $generated" -ForegroundColor Yellow
    Write-Host ""
}

Write-Host ""
Write-Host "  NetProof - neutral network-change validation" -ForegroundColor Cyan
Write-Host "  ----------------------------------------------------------" -ForegroundColor DarkGray
Write-Host "  Open http://127.0.0.1:8000  - Ctrl+C to stop" -ForegroundColor Gray
Write-Host ""

try {
    Push-Location $backend
    & $py -m uvicorn main:app --host 127.0.0.1 --port 8000
}
finally {
    Pop-Location
}
